name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Set a branch to deploy so that it doesn't deploy every branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install and Build Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'
      - name: Install Jekyll and dependencies
        run: |
          gem install jekyll bundler
          bundle install
      - name: Build Jekyll site
        run: bundle exec jekyll build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
